### ISSUE TITLE
[Request] Update from "upstream"

### ISSUE THREAD

**Issue by askotx** [libretro/mgba#100]
Lastest upstream has many fixes for SGB implementation, so any update will be great.

**Comment by fr500** [comment]
afaict updates are coming from upstream when @endrift deems the changes
ready, she sent the last rebase herself.

**Comment by endrift** [comment]
News to me. That was just me saying 0.6 is done, time to track 0.7.

**Comment by fr500** [comment]
Ah sorry about that, misunderstanding.

**Comment by askotx** [comment]
I'm lost, should I close this request?

**Comment by endrift** [comment]
Nah, but I should poke @sergiobenrocha2.

**Comment by sergiobenrocha2** [comment]
Updated the repo, download/update the core in a few minutes again

**Comment by askotx** [comment]
Thanks for your responses!!
