### ISSUE TITLE
No Super Game Boy borders with Pokemon Yellow.

### ISSUE THREAD

**Issue by bslenul** [libretro/mgba#106]
Hey!

Love the recent addition of SGB borders for Game Boy games :D However it seems there's a bug with Pokemon Yellow (I tried USA/Europe and French roms) and it seems to be because it is recognized as a GBC game (`(GBC,SGB Enhanced)` in the filename, AFAIK it's the only GB game with that).

So I tried to go to core options and put `Game Boy model` to Game Boy but it starts like a normal GB game without borders, and I tried Super Game Boy, the screen is smaller with borders all around but they stay white.

![pokemon - yellow version - special pikachu edition usa europe gbc sgb enhanced -180618-102930](https://user-images.githubusercontent.com/33353403/41525828-9267bd36-72e2-11e8-96d5-2824cde3dbea.png)

RetroArch 1.7.3, latest version of mGBA core (0.7-WIP 9dd7301 as I'm writing), Windows 10 and Linux.

**Comment by hizzlekizzle** [comment]
Did you try just renaming it to *.gbc?

**Comment by bslenul** [comment]
No, maybe I explained the problem poorly, I'll try to be more clear:

* Pokemon Yellow is a Game Boy game, with Game Boy Color and Super Game Boy enhancements.
* GBC enhancement works fine as you can see on the screen below, SGB enhancement however doesnt work and that's the issue.
* With `Game Boy model` set to `Autodetect`, the game runs like a GBC game:

![pokemon - yellow version - special pikachu edition usa europe gbc sgb enhanced -180619-000655](https://user-images.githubusercontent.com/33353403/41564986-14c2acd8-7355-11e8-9373-55b6627b8c8a.png)

(same behavior with the option set to `Game Boy Color` or `Game Boy Advance`)
* With the option set to `Game Boy` the game runs like a GB game:

![pokemon - yellow version - special pikachu edition usa europe gbc sgb enhanced -180619-000729](https://user-images.githubusercontent.com/33353403/41565030-4547f50c-7355-11e8-96d1-7b1962d16b9c.png)

* With the option set to `Super Game Boy`, instead of having the SGB borders [**like this**](http://i47.tinypic.com/vziw02.png), the borders are white:

![pokemon - yellow version - special pikachu edition usa europe gbc sgb enhanced -180619-000802](https://user-images.githubusercontent.com/33353403/41565085-7d4bb89e-7355-11e8-8370-cd9253f2a791.png)

**Comment by endrift** [comment]
For reference, only the last of these scenarios is a bug.

**Comment by hizzlekizzle** [comment]
Oops, my mistake: I was thinking of the Pokemon Gold beta, which has an *.sgb file extension but works fine with borders and all if you change the file extension to *.gbc. So, plz disregard.

**Comment by bslenul** [comment]
Oh yeah, it was just to describe how the core behave with each value for this core option. The problem is only with Super Game Boy enhancement not working.

Also I don't think it's helping but I just tried with the standalone emulator and same result, no SGB colors/borders.

**Comment by endrift** [comment]
Please file an issue on the main repository then. It'll get fixed there and then the fix can be merged here.

**Comment by bslenul** [comment]
Done: https://github.com/mgba-emu/mgba/issues/1104

Should I close this one then?
