### ISSUE TITLE
Audio buffer size problem

### ISSUE THREAD

**Issue by vanfanel** [libretro/mgba#109]
Hi,

With this core, using an audio latency < 50 ms with max_swapchain = 2 causes distorted audio.
This happens on x86_64 and ARM (rpi3), and it's not related to high CPU usage.
I believe this core has a bigger internal audio buffer than other cores, doesn't it? Can it be somehow reduced so it works fine with low-latency audio?

**Comment by vanfanel** [comment]
@jdgleaver That was a very good work, thanks, really. Now this core supports small audio buffers and behaves much, much better in low-latency setups!

**Comment by jdgleaver** [comment]
I'm happy to help! :)
