### ISSUE TITLE
No git version

### ISSUE THREAD

**Issue by fr500** [libretro/mgba#116]
The method we had to embed the git version seems to be no longer working which makes tracking breakage really difficult.

**Comment by twinaphex** [comment]
Should we report this to upstream so that it can be implemented there for the libretro core? Does upstream have the static Makefile already?

**Comment by fr500** [comment]
we just do

```
GIT_VERSION := " $(shell git rev-parse --short HEAD || echo unknown)"
ifneq ($(GIT_VERSION)," unknown")
	CFLAGS += -DGIT_VERSION=\"$(GIT_VERSION)\"
endif
``` 

in the makefile and then if GIT_VERSION is defined we append that to the core version

**Comment by sergiobenrocha2** [comment]
Actually, it's working [on Linux]

Is it working just for some platforms? I can't see it on Android

**Comment by fr500** [comment]
Ah maybe we missed it on android it could be, let me check

**Comment by fr500** [comment]
Ah for android we use leiradel's cross makefiles so I guess that's the reason.
I'll try to fix it up and later on make a jni makefile

**Comment by fr500** [comment]
Made a PR should be good enough for now.
