### ISSUE TITLE
(Android) Lower API level from 21 to say 9

### ISSUE THREAD

**Issue by twinaphex** [libretro/mgba#122]
@leiradel Some users are complaining to me that the MGBA libretro core can no longer run on Android 4.x. I looked quickly at the Makefiles and I see that it requires API level 21. API level 21 would mean you needed Android 5.x as a minimum, so what the user reports checks out.

Can we lower the API level so that this user can run mGBA again on his device? Thanks in advance.

Here is the message he sent me on Discord -

[quote]
I have the Snail Much W1 and the mGba core no longer works after the last update and I've tried older releases however they no longer work either. I did not keep a back up of any of the cores. That is a really odd phone and way over complicated but I have enjoyed using Retroarch on it. I think it was the first octa core Android phone. It's running Android 4.2.2. It isn't the only device that has had that issue arise. I have an old Samsung Galaxy Tab 2 7.0 also running Android 4.2.2 and it has all so stopped working on it. Any ideas?
[/quote]

**Comment by leiradel** [comment]
It seems that it was changed in the last cross-makefiles update. I don't know why it was changed, and I personally don't have any requirements for API levels, so I believe it can be changed to something else.

**Comment by meepingsnesroms** [comment]
Fixed: https://github.com/libretro/mgba/pull/127
