### ISSUE TITLE
Alex Rider - Stormbreaker character moving issue

### ISSUE THREAD

**Issue by Yabuato** [libretro/mgba#125]
I'm on Android,32bit RA,latest mGBA core
Sorry for my English,I made a recording instead

https://youtu.be/HP-Z3JyIyO4

**Comment by Yabuato** [comment]
Okay,looks like my issue had been ignored,this problem still exist in newest version,I didn't try the standalone(I don't use computer to play games personally),probably it's a libretro port issue,I don't know.

It's funny the author claims mgba is the more accuracy than other gba emulators,but I found many accuracy issues in mgba that don't exsit in other gba emulators.

Your accuracy emulator is not that accuracy.

**Comment by endrift** [comment]
Try actually reporting the bugs then.

**Comment by Yabuato** [comment]
The game name
Platform (Android)
The video shows the problem

I can comfirm the version 0.6.1 has no this issue,the character walks like a normal human.

What other infos do you need?

**Comment by Yabuato** [comment]
Or you want the bugs I mentioned that don't exist in other emulators?

Too far too many,I can't remember,I found those bugs by filtering the games in  a full romset one by one months ago,some issues don't have an severe influence on actual gameplay so I just ignored.

**Comment by endrift** [comment]
The 0.6.1 bit really helped me track this down. Fixed in 01a96c6313216f9111cc8670f45c30d588c8f97d, but you'll need to wait for it to get merged into the libretro branch.

I had meant to fix this but because the report isn't in the main repo I kept forgetting about it.

**Comment by Yabuato** [comment]
Okay that's my bad. I apologize and thanks for taking time to fix it.

**Comment by Yabuato** [comment]
Seems it still hasn't been merged?

**Comment by Yabuato** [comment]
This issue has finally been fixed,thanks.Close issue.
