### ISSUE TITLE
Homebrew ROM (Airaki!) shows Checksum Error on launch

### ISSUE THREAD

**Issue by richiegigabit** [libretro/mgba#130]
First of all thank you so much for the mGBA core development.

The issue I come with today is very specific. Essentially, modern day rom developers are adding emulation checksum errors so that their developed titles cannot be played on emulators (or RetroArch cores in this case), but rather play perfectly fine and enhanced with color on physical GameBoy hardware. However, there are emulators that can actually run the title because that boast accuracy to actual GameBoy/GameBoy Color hardware.

The rom I would like to add support for is called Airaki! and it is available for download [here](http://blog.gg8.se/wordpress/2014/05/14/furrteks-airaki-quick-game-review-and-rom-dump-download/). The page lists detail of what happens when the game is emulated, but it displays a Checksum Error screen that reads "Fuck You, Emulator!" on launch. I am hoping to get support on the mGBA core for Retroach since it is the best speedwise in reference to GameBoy and GameBoy Color (preferably the NES Classic retroarch).

The rom however does work on SameBoy and BGB emulators on computer in case you wanted to test it through other avenues, but I do understand emulators and cores are very different so I want to say thank you once again.

**Comment by endrift** [comment]
This was just fixed upstream.

**Comment by keithbowes** [comment]
WFM.  Surely this issue should be closed now.
