### ISSUE TITLE
mGBA Update to 0.7.2 or 0.8.0 (git)

### ISSUE THREAD

**Issue by ToniBC** [libretro/mgba#142]
Hello, I put this here because you always tell me to put it so that it remains a record.

Since February 24 the emulator was updated with several improvements and it would be interesting to update the core of libretro as well.

The current version is 0.7.1 with many improvements and corrections.

Surely someone will be working on it, but if not, someone can see and get with the changes.

Greetings and thanks for your time and effort.

**Comment by ToniBC** [comment]
I see that it was updated, so nothing, thank you very much for having this updated core that is the best in the GBA emulation.

**Comment by ToniBC** [comment]
Apparently for some problem it was returned to 0.7, so I leave this as always for anyone who can take it into account to update to 0.7.2.

The next version and the svn of 0.8.0 incorporate the option of HD, there is a desire to try this in libretro.

Thank you very much for the work and effort.

**Comment by endrift** [comment]
When was it returned to 0.7? It should be on 0.8 (git, not svn) still. Maybe the manually edited version string is wrong.

**Comment by ToniBC** [comment]
That's why I mentioned it, I do not know why, but it comes out that is 0.7 and in git it says "Revert" Merge remote-tracking branch 'upstream / 0.7 ".

**Comment by iGom** [comment]
The current kernel available in RetroArch is in version 0.7.0 ae3dc96

**Comment by iGom** [comment]
> 
> 
> Apparently for some problem it was returned to 0.7, so I leave this as always for anyone who can take it into account to update to 0.7.2.
> 
> The next version and the svn of 0.8.0 incorporate the option of HD, there is a desire to try this in libretro.
> 
> Thank you very much for the work and effort.

The current core available in RetroArch is in version from commit ae3dc96

**Comment by hizzlekizzle** [comment]
It should report v0.8 git-hash now: https://github.com/libretro/mgba/commit/9c8a1a598d04e764df5f848ff619869a9c3f6ad8

**Comment by ToniBC** [comment]
Thanks, it seems that the emulator is almost up to date.
