### ISSUE TITLE
Missing backgrounds in KOF 95

### ISSUE THREAD

**Issue by neogeo-user** [libretro/mgba#162]
(Also filed [upstream](https://github.com/mgba-emu/mgba/issues/1508).)

Tested on mGBA 0.7.0 from binary, commit [8d0bf2a](https://github.com/libretro/mgba/tree/8d0bf2a) and 0.8.0 from source (commit [8cf7b43](https://github.com/libretro/mgba/tree/8cf7b43)).

Playing King of Fighters 95, there seem to be missing backgrounds; it appears in the intro screen and also during battle. These appear fine with Gambatte

Happens in both SGB (what I'm glad that mGBA supports) and regular GB modes.

mGBA SGB:
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-091834](https://user-images.githubusercontent.com/54290622/63415905-5b247d80-c3f6-11e9-901e-7917e7ed2ee3.png)
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-091848](https://user-images.githubusercontent.com/54290622/63415912-5d86d780-c3f6-11e9-959f-f16e1bdb8809.png)

mGBA GB:
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-093455](https://user-images.githubusercontent.com/54290622/63416262-07fefa80-c3f7-11e9-9d96-1ca1c68c6adb.png)
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-093507](https://user-images.githubusercontent.com/54290622/63416273-0a615480-c3f7-11e9-9b02-e9c9e2ae044d.png)

Gambatte:
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-092028](https://user-images.githubusercontent.com/54290622/63415935-69729980-c3f6-11e9-8ce9-84d8bc078cd2.png)
![King of Fighters '95, The (USA) (SGB Enhanced)-190821-092038](https://user-images.githubusercontent.com/54290622/63415939-6b3c5d00-c3f6-11e9-828b-9cb53d3df532.png)

Thank you for your effort.

**Comment by Testsr** [comment]
![image](https://user-images.githubusercontent.com/31809837/73993172-86e7ef80-49a5-11ea-9a20-64cb87510abe.png)

![image](https://user-images.githubusercontent.com/31809837/73993143-746db600-49a5-11ea-9135-388bdabdf5d5.png)

**Comment by Testsr** [comment]
Proof by contradiction. You can close the issue now.
