### ISSUE TITLE
Update to 0.8 Beta 1

### ISSUE THREAD

**Issue by RobLoach** [libretro/mgba#165]
https://mgba.io/2019/10/20/mgba-0.8-beta1/

**Comment by NejiHyuga900** [comment]
I hope the Android version of the mGBA core also gets updated to 0.8 beta 1 as the Android core has been stuck on version number 0.7.0 ae3dc96.

**Comment by negativeExponent** [comment]
im interested in that enhance graphics transforms and XQ sound thingies, these should try and improve and bring back some the lost details in the system. hope they are/will be in the libretro core.

**Comment by endrift** [comment]
This can be closed. The core has been updated past beta 1 by now.

**Comment by RobLoach** [comment]
Thank you so much for all the help! Absolutely love all the progress on mGBA lately. :heart:
