### ISSUE TITLE
Solar sensor doesn't work

### ISSUE THREAD

**Issue by gary-ts** [libretro/mgba#168]
Solar sensor doesn't work.
I tested "Boktai - The Sun Is in Your Hand (USA)".
It works fine on mGBA-0.7.3-win32 (through wine), 
but it doesn't work on libretro-mgba-master (Linux x64).
See also this thread please:
https://github.com/mgba-emu/mgba/issues/1584

**Comment by negativeExponent** [comment]
L3/R3 hotkey to adjust solar sensor level does not work if you are already using a patched rom (one of those roms that uses button combinations to adjust solar sensor)

**Comment by gary-ts** [comment]
Solar sensor works fine on upstream mgba without a bios.
I disabled a bios on libretro-mgba. Solar sensor doesn't work.

**Comment by Testsr** [comment]
Does the  Solar Sensor work with the bios?

**Comment by gary-ts** [comment]
It seems that no one play Boktai.
I close this issue.
