### ISSUE TITLE
[Bug] SGB, GB games not working with achievements

### ISSUE THREAD

**Issue by askotx** [libretro/mgba#182]
I've tried some games like DK Land and if no save then it triggers four achievements at start game, also Kirby Dream Land 2 no achievement is unlocked after any trigger like getting Hamster Rick, getting a Rainbow Drop, etc, Tested Super Mario Land 2 earning 20 lives achievement and nothing. I have not tried a Game Boy Color game.
mGBA version 0.8.1 f8719e1 on retropie raspberry 3.

**Comment by Sanaki** [comment]
GB, GBC, and by extension SGB are known not to have achievement support on this core. Getting that fixed would be fantastic.

To avoid future headaches, consult this list:
https://libretro.readthedocs.io/en/latest/guides/retroachievements/#cores-compatibility

**Comment by askotx** [comment]
Thanks, then I must close this issue

**Comment by Sanaki** [comment]
No need to close it. It is a problem in the core that could potentially be resolved. Tracking issues is a good thing.

**Comment by askotx** [comment]
Ok, I will re-open it

**Comment by negativeExponent** [comment]
![Screenshot_20200422_133437](https://user-images.githubusercontent.com/54053706/79944483-33624980-849e-11ea-8afc-3c41022258ea.png)

it should work if added correctly. any reason why it was not implemented?

**Comment by Sanaki** [comment]
Not that I'm aware of. Could have just been an oversight.

**Comment by askotx** [comment]
That was fast, I can get that Hamster now, thanks and good job!
