### ISSUE TITLE
Hello Kitty Collection: Miracle Fashion Maker(J) does not boot

### ISSUE THREAD

**Issue by Michael-Prince-Sharpe** [libretro/mgba#187]
The answer to the reason for this is here https://mgba.io/2020/01/25/infinite-loop-holy-grail/
It seems that the libretro core is behind the main standalone version in this case.

**Comment by Awakened0** [comment]
This commit is the one that's supposed to fix it: https://github.com/mgba-emu/mgba/commit/93633ea60524ac2983e747e13656b896544299cf

Looks like the changes from that commit are still missing in this repo. Even after the 0.8.3 update.

**Comment by endrift** [comment]
Those changes aren't in 0.8.3. For a reason, too. They required API and savestate changes, which makes them unsuitable for a point release.

**Comment by Awakened0** [comment]
Understandable, thanks for the explanation!

**Comment by endrift** [comment]
Yes, 0.9 got merged so this should work now.
