### ISSUE TITLE
Crash on unload from libretro frontends that don't populate retro_camera_callback

### ISSUE THREAD

**Issue by Sanaki** [libretro/mgba#188]
When initializing retro_camera_callback, some libretro frontends (RALibretro in this case) simply return false due to lack of camera support. On unloading mGBA, this reliably causes a crash when the nonexistent camera can't be shut down.
https://github.com/libretro/mgba/blob/master/src/platform/libretro/libretro.c#L1678

Thanks @Jamiras for pinpointing the source of the problem.

**Comment by Jamiras** [comment]
I think this was fixed by https://github.com/mgba-emu/mgba/pull/1931. I can no longer reproduce it.
