### ISSUE TITLE
[Wii] Error on loading 32 MB roms

### ISSUE THREAD

**Issue by askotx** [libretro/mgba#19]
Some 32 MB roms like Kingdom Hearts: Chain of Memories, crash on loading, even if this rom can fit well on MEM2 memory, any other size rom, plays fine.

**Comment by sergiobenrocha2** [comment]
Related: http://libretro.com/forums/showthread.php?t=4430

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#24
