### ISSUE TITLE
PS3 - Since build a2f10c3 _initSensors makes core unusable

### ISSUE THREAD

**Issue by crystalct** [libretro/mgba#211]
With _initSensors(); all input systems on PS3 are breaked, making the core unusable.

**Comment by endrift** [comment]
Well that's...not...a real fix at all. It'd be okay for a temporary workaround, but it also merged in an incorrect fix for a warning. @twinaphex, you've violated the PR rubber stamp agreement we had. That didn't take very long...

**Comment by endrift** [comment]
Also that sensors code is what's causing the Android crash (#199) in the first place so _maybe_ if you fixed it it'd be the right fix for this too.

**Comment by crystalct** [comment]
I'm tiring to solve all issues from PS3 point of view (i have hardware and sdk for that). Now v0.8.4 intruduced somewhere a segmantation fault more complex than _initSensors(), cause many source lines changed with commit 2a221b3.
For now PR #212 just remove _initSensors() only for PS3 build, and yes is a workaraound... i just thought what sensors the PS3 has... none, thinking about movement sensors.... i will take a look after segmentation fault.

**Comment by endrift** [comment]
Sorry, I was talking about this: https://github.com/libretro/mgba/commit/54a1f8ebc0989676b7b1d6a43bf3047c2ffe746e#diff-d2b005acdc7ac7cf1e97088828dedc7536894a7f180b48c270b334d7078adc8cR65-R69 which is unrelated to the point of that PR and I would have complained about had it not gotten rubber stamped before I noticed. As I said, the ifdefs are a _temporary_ fix and I wouldn't have held up a PR over.

**Comment by crystalct** [comment]
You are talking about only chnages about initsensor, right? Because fisrt two are only corrections necessary for PS3 enviromnet.
Max-path = 4096 is wrong on FS filesystem of PS3 and gettimeofday doesn't exist on Sony SDK for PS3. 
The correct ways should be a PR for first two Ps3 environment specific and another for walkaround  for issues #211?

**Comment by endrift** [comment]
I'm talking about the changes to common.h. Particularly, I'm talking about putting the prototype in that file. There was a PR merged recently that implemented that function in formatting.c; thus, the prototype should accordingly be put in formatting.h. You didn't necessarily know that, but it got merged before I had a chance to ask you to fix it.

**Comment by crystalct** [comment]
Ok... i can remove it.... and i can put in a better position ..or remove it at all and keep waring  "implicit declaration of function 'gettimeofday'".... what do you suggest me?

**Comment by endrift** [comment]
I'll get back to you on that tomorrow. It's too late at night for me to really be thinking about this. I guess I should get around to trying to do the actual sensors fix too since no one else has yet. It hasn't really been very high up on my list of priorities lately.

**Comment by crystalct** [comment]
Ok...In italy is lunch time ^_^ good night
