### ISSUE TITLE
PS3 - Since commit 2a221b3 a segmentation fault appeared

### ISSUE THREAD

**Issue by crystalct** [libretro/mgba#213]
.... when you try to start a rom. I'm looking for solve it.

**Comment by crystalct** [comment]
Ok ... last commit working about v0.8.3 is 4c07fa0
then 2a2221b3 makes many changes for new v0.8.4

**Comment by crystalct** [comment]
Got it.
file `src/util/hash.c` function `static FORCE_INLINE uint32_t getblock32 ( const uint32_t * p, int i )` 
from
`return p[i];`
to
```
uint32_t ret;
LOAD_32LE(ret, i << 2, p);
return ret;
```

**Comment by endrift** [comment]
If that's causing a segfault, that's kinda bad news. It'll take a fair bit of effort to fix that properly, since this implies that unaligned byte-swap loads on the PS3 don't work. I need to figure out a way to get that function to work with unaligned loads, or force it to be aligned.

**Comment by crystalct** [comment]
__asm__ used for LOAD_32LE (and others LOAD and STORE macros) works only for HW_RVL and GEKKO.
Now CELL works, too.

**Comment by endrift** [comment]
I understand what the point is, but the way it's done is a little...well, I'm not fond of it, to be frank. For what it's worth, that ASM is tested on more than just ppc32. But I'm going to see if I can tweak it some to see if I can get it working in a bit more...unified manner.
