### ISSUE TITLE
Cheats don't work on opendingux builds

### ISSUE THREAD

**Issue by kayladmae** [libretro/mgba#220]
1.9.0 mGBA (0.8.4 dfcba77)
Part of the 1-7-2021 nightly
RG350M

Issue occurs on any GBA game

Cheats from local files don't work, and the cheat search functionality doesn't either. The "Start or Restart Cheat Search" option under the in-game "Start or Continue Cheat Search" menu doesn't react when you press A on it.

These features do work for gPSP but obviously that emulator runs GBA games very poorly

**Comment by kayladmae** [comment]
Just realized I gave the wrong information. The issue is in gPSP, and MGBA works despite it not supposed to run GBA games.

**Comment by endrift** [comment]
I don't understand. If this is an issue in gpSP why are you reporting it on the mGBA repo? And why do you say mGBA is not supposed to run GBA games?
