### ISSUE TITLE
[Regression after 0.8.3] Runahead causing artifacts, skips and stutters with some games

### ISSUE THREAD

**Issue by Ryunam** [libretro/mgba#222]
With the libretro version of mgba updated to 0.8.4, as downloaded from the online updater in RA, some visual artifacts and stutters may occur in certain games when using Runahead, either with single istance or with the second instance mode. These issues do not seem to happen at all with version 0.8.3 of the core.

I reproduced this in at least one game that I have repeatedly tested: Rockman Zero (Japanese version of Megaman Zero). Here's what I did:

- In RA, under Settings -> Latency, set Runahead to ON, 1 frame of reduced latency and Second Instance to ON.
- Let the introduction movie play or fast-forward through it, then when you gain control of the character kill all the soldiers in the very first area.
- Then while staying in the first area start mashing buttons quickly: use L and R to slide left or right, while pressing Y repeatedly to  shoot and A to jump around.
- After a few seconds, you may notice that the lights from the ceiling judder around or other artifacts start appearing onscreen. Audio continues to play perfectly fine, but while mashing buttons (or playing normally in the later sequences, where lots of enemies start to assault you) a visual stutter can happen quite often. This issue is not present with the libretro core on version 0.8.3: everything plays smoothly with Runahead Second Instance.
- On at least one occasion I've had the game soft-lock on the first area, by simply enabling and disabling Second Instance from the Latency Menu. Audio continued to play as normal, while the character remained frozen in mid-air after a jump.

**Comment by bslenul** [comment]
Just tried Rockman Zero (on Windows 10 with latest version of the core), I didn't notice any artifacts, but after spamming the buttons I get a complete freeze of RetroArch for ~30 seconds:

https://user-images.githubusercontent.com/33353403/106656097-83784b80-659a-11eb-8f99-a16d472cbea3.mp4

(1st freeze ends at 0:44, then as soon as I press a button it freezes again)

Few things I've noted:

* Each time I press and each time I release a button this appear in logs (these 2 lines appear in 0.8.3 as well):
```
[libretro INFO] Savestate: Loading savedata
[libretro INFO] Savestate: Loading RTC
```
* Sometimes this line appears:
```
[libretro WARN] GBA Savestate: Savestate has unaligned PC and is probably corrupted
```
* When it freezes logs get spammed with this:
```
[libretro ERROR] GBA Memory: Jumped to invalid address: 0901C1E4
[libretro WARN] GBA: Illegal opcode: e710b710
```

Without second instance it's even worse, I don't even have to press anything, it spams logs as soon as the game starts then the freeze happens by itself.

**Comment by Ryunam** [comment]
Okay, I have some more data. I tried to record the same scene with both 0.8.3 and 0.8.4. This is with Runahead set to ON, Runahead Frames set to 1 and Second Instance set to ON.

**0.8.4** - Around 0:04, pay attention to the pillars of light suddenly getting displaced, as well as the image stuttering visibly:

https://user-images.githubusercontent.com/17614150/106746927-81a69a80-6623-11eb-8db5-69a49e734d5d.mp4

**0.8.3** - Gameplay is smooth with Runahead. There's no displacement of the light pillars or other hiccups:

https://user-images.githubusercontent.com/17614150/106747537-57091180-6624-11eb-9fcf-ed962471007a.mp4

I have also tried to perform a bisect here downstream. Unfortunately, there's a lot of skips when doing that, due to missing makefiles and other errors, so I could not narrow the issue down to one single bad commit.

However, while testing I could see that up to 11d194f0988178a53dbfbe20699c5fad658d39e5 everything worked fine. The issue starts happening between 67cf9b78b3d09a423874cdb3002efdd0a46d74b1 and 2c4f6bb0f306c93e363d260d62ea9bf35c4c5de7, so it's safe to assume that it was introduced with the 0.8.4 update.

Finally I have noticed some issues on the upstream repository that have to do with savestates, which might also be related to this problem based on the logs posted by @bslenul.

https://github.com/mgba-emu/mgba/issues/2031
https://github.com/mgba-emu/mgba/issues/2008

I wanted to try and do a bisect upstream as well, but I could not figure out how to build a libretro core there.

**Comment by bslenul** [comment]
Ah weird, looks like maybe when you're getting these artifacts I'm getting these huge freezes instead :p 

And yeah, couldn't make a proper bisect as well, I'm not an expert in compilation and I had issues with commits without Makefile and ended up skipping like 20-30 commits... The last commit that worked for sure for me was 1326a96c9ee4ac5650417b36586a5c78072cf60e, which seems to be the last one before the version bump. So yeah, not super helpful sorry, I wish cmake didn't give me so much trouble with this core...

**Comment by endrift** [comment]
If it's related to the unaligned PC issue, that bug has already been fixed upstream. You can try building an upstream commit and seeing if that fixes the issue.

**Comment by bslenul** [comment]
No idea if it fixes the artifacts issue for Ryunam but it definitely fixed the huge freezes in my case! Thank you for your answer! 👍

**Comment by Ryunam** [comment]
Thank you @endrift for quickly looking into this! It's definitely much appreciated. I followed your instructions, cherry-picked the upstream commit that you pointed out and, lo and behold, Runahead now works perfectly with Rockman Zero. :)

Is it okay to backport that single fix and submit a PR to this downstream repo, or would you rather do a general update and/or handle this differently? Let me know what's your preferred course of action.

**Comment by endrift** [comment]
This is a pretty serious bug so an out-of-band update is not unwarranted. However, there may be other serious bugs that should get fixed if an out-of-band update is to be issued. I should try to collect a list.

**Comment by Ryunam** [comment]
Hi @endrift, I was just wondering if you had any news on when an update that fixes this issue might be coming. 

Right now I am still using a self-built core with that one commit that fixed Runahead cherry-picked, as per your instructions, but having an up-to-date core aligned with upstream with the fix permanently "ingrained" in it would be definitely desireable. 

Otherwise I can maybe submit a PR in the meantime and backport that single commit that addresses this while we wait for a proper mgba update, but I'd rather hear what works best for you.

**Comment by endrift** [comment]
Hi, sorry for the delay. I've been desperately trying to finish up the 0.9 release for the past two months and I'm _really_ close now, but I also can't guarantee when it'll happen. You're welcome to submit the PR and I can approve/merge it, but also it'll (hopefully) be pretty short-lived before I merge in 0.9.0.

**Comment by Ryunam** [comment]
Thank you, no worries for the wait. I have just submitted a PR with the fix backported from upstream. Definitely excited for the 0.9.0 release as well!

**Comment by Ryunam** [comment]
I think this can be closed for now!
