### ISSUE TITLE
 gyroscope emulation and rumble support on iOS

### ISSUE THREAD

**Issue by illando** [libretro/mgba#229]
It seems that using the mgba core,  gyroscope emulation and rumble supported on other device like switch.
Would be possible to hook up the core also to the iphone hardware?

[https://youtu.be/wnXJT672pU0](url)

**Comment by endrift** [comment]
This is on RetroArch itself adding gyroscope and rumble support to the frontend; it's already implemented in the core if the frontend supports it.
