### ISSUE TITLE
Applying Game Boy (GB) cheats crashes mGBA

### ISSUE THREAD

**Issue by summonthethunder** [libretro/mgba#235]
Windows 10 64-Bit
RetroArch 1.9.5
Latest mGBA core download and core info files

Issue: Whenever I attempt to add a cheat to a Game Boy (GB) game, RetroArch freezes, then crashes back to desktop.  I tried three separate GB games with the same results.  Crash log attached.

[crash-210616-200526.log](https://github.com/libretro/mgba/files/6667114/crash-210616-200526.log)

**Comment by endrift** [comment]
Can you give an example of a cheat you're trying to add?

Also that crash log indicates RetroArch itself thinks the cheat adding function (`retro_cheat_set`) isn't present, despite the fact that it is in the source code.

**Comment by summonthethunder** [comment]
Sure, here is an example:

Druaga no Tou (Japan).cht
Infinite Time - 0127C2C2
Invincibility - 18D-20F-2AA

Crashes immediately upon applying the above cheats via RetroArch's Cheat menu.

A possible point of reference: I tried the same game with the same cheat codes in Gambatte and they both work with no issues.

**Comment by summonthethunder** [comment]
Hello,

Is there an update on this issue by chance?  Is there anymore information you need from me?

**Comment by endrift** [comment]
Sorry about the delay. It should be fixed now.
