### ISSUE TITLE
Turbo A+B Seem to be Shifted onto Regular B [Regression]

### ISSUE THREAD

**Issue by Awakened0** [libretro/mgba#237]
The latest Win64 buildbot build (64f211cde24ea66de8b5382359397f67a5464603) has a problem where A and B seem to act as both Turbo A and Turbo B when pressed. The actual Turbo button inputs no longer do anything themselves, so it's like they were somehow shifted onto the regular A and B inputs. The previous build I have (c7dba6b) works properly.

**Comment by Sanaki** [comment]
Just checked on Linux. A works fine, B is meshed A+B turbo, and turbo A, turbo B, turbo R, and turbo L all fail to do anything.

**Comment by Awakened0** [comment]
I noticed it acting weirdly with B first and kinda haphazardly tested A before opening this, so A is probably fine.

**Comment by endrift** [comment]
Should be fixed now.

**Comment by Sanaki** [comment]
I can confirm that my ability to violently twerk via button press in Harmony of Dissonance has been restored. Looks good now, thanks.

**Comment by endrift** [comment]
Sorry about that, there was a merge conflict that I resolved wrong.
