### ISSUE TITLE
Insane spam in log file

### ISSUE THREAD

**Issue by bslenul** [libretro/mgba#265]
The core spams non-stop this kind of stuff in log file:
```
[libretro INFO] GBA DMA: Starting DMA 3 0x03007EF8 -> 0x02000000 (8500:0000)
[libretro INFO] GBA DMA: Starting DMA 3 0x03007EF8 -> 0x03000000 (8500:1F80)
[libretro INFO] GBA DMA: Starting DMA 3 0x03007EB8 -> 0x05000000 (8100:0200)
[libretro INFO] GBA DMA: Starting DMA 3 0x0800023C -> 0x03002AA0 (8000:0074)
[libretro INFO] GBA DMA: Starting DMA 3 0x08001840 -> 0x03002B88 (8000:01C8)
[libretro INFO] GBA DMA: Starting DMA 1 0x030023E0 -> 0x040000A0 (F660:0004)
[libretro INFO] GBA DMA: Starting DMA 2 0x03002500 -> 0x040000A4 (F660:0004)
```
After 5-10mn my log file was 120MB with almost 2 million lines in it... On Windows 10 if it matters.

[logs.zip](https://github.com/libretro/mgba/files/9292902/logs.zip)

**Comment by endrift** [comment]
Does Retroarch really have the log level set that high by default?

**Comment by bslenul** [comment]
Yeah, "INFO" is the default logging level.

**Comment by bslenul** [comment]
Would that be an acceptable fix (making the line only print on DEBUG level for the Libretro core)?:
```cpp
#ifndef __LIBRETRO__
		mLOG(GBA_DMA, INFO, "Starting DMA %i 0x%08X -> 0x%08X (%04X:%04X)", dma,
		     currentDma->nextSource, currentDma->nextDest,
		     currentDma->reg, currentDma->count & 0xFFFF);
#else
		mLOG(GBA_DMA, DEBUG, "Starting DMA %i 0x%08X -> 0x%08X (%04X:%04X)", dma,
		     currentDma->nextSource, currentDma->nextDest,
		     currentDma->reg, currentDma->count & 0xFFFF);
#endif
```
Sounds like a dumb question but I'm not a dev so I prefer to ask before sending a PR :p

**Comment by endrift** [comment]
Assuming that's the right ifdef (I think it is), that would be fine, though you shouldn't surround the whole function call, just the first line. The rest of the lines are the same between them. I was just trying to figure out if I should bump down the log level for this to DEBUG, or if this is the better approach.

**Comment by bslenul** [comment]
> you shouldn't surround the whole function call, just the first line.

Yeah that's what I did at first but it appeared weirdly when I put in the issue, the endif was white:
```cpp
#ifndef __LIBRETRO__
		mLOG(GBA_DMA, INFO, "Starting DMA %i 0x%08X -> 0x%08X (%04X:%04X)", dma,
#else
		mLOG(GBA_DMA, DEBUG, "Starting DMA %i 0x%08X -> 0x%08X (%04X:%04X)", dma,
#endif
		     currentDma->nextSource, currentDma->nextDest,
		     currentDma->reg, currentDma->count & 0xFFFF);
```
 so I thought maybe I did something wrong (although it compiled and worked just fine)...

> if I should bump down the log level for this to DEBUG

Again I'm not a dev but it'd make sense to me, doesn't look like the kind of info you'd want outside of debugging :p
