### ISSUE TITLE
Update the mgba core based on the new mgba 0.10.0

### ISSUE THREAD

**Issue by RFL0WGitPR** [libretro/mgba#272]
mgba recently updated to ver. 0.10.0

There's a lot of changes and fixes
RetroArch core of mgba will benefit from

Check the Change log 

https://mgba.io/2022/10/11/mgba-0.10.0/

**Comment by bslenul** [comment]
Already done (thank you Ryunam btw ❤️ ): #271

**Comment by schmurtzm** [comment]
Can be closed ;)
