### ISSUE TITLE
[HowTo] How to build it for iOS and VisionOS

### ISSUE THREAD

**Issue by Phantomxm2021** [libretro/mgba#289]
We are developing an emulator for **VisionOS** but we don't know how to build it from source.
Does anyone know?

**Comment by warmenhoven** [comment]
Every core in the libretro project that is built and available on the buildbot uses the gitlab CI infrastructure. They all have a [.gitlab-ci.yml](https://github.com/libretro/mgba/blob/master/.gitlab-ci.yml) file, and almost all of them reference the [helper template scripts](https://git.libretro.com/libretro-infrastructure/ci-templates).

For iOS for mgba, the command that is executed is:
`make -C . -f Makefile.libretro platform=ios-arm64`

**Comment by Phantomxm2021** [comment]
> Every core in the libretro project that is built and available on the buildbot uses the gitlab CI infrastructure. They all have a [.gitlab-ci.yml](https://github.com/libretro/mgba/blob/master/.gitlab-ci.yml) file, and almost all of them reference the [helper template scripts](https://git.libretro.com/libretro-infrastructure/ci-templates).
> 
> For iOS for mgba, the command that is executed is: `make -C . -f Makefile.libretro platform=ios-arm64`

Thanks. But when I build for iOS I get a nerror, do you know how to fix it?
```log
ld: building for 'iOS', but linking in object file (/Users/xxx/Downloads/mgba-master/src/arm/arm.o) built for 'macOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mgba_libretro_ios.dylib] Error 1
```

**Comment by warmenhoven** [comment]
`make clean`

Looks like you previously built it for macOS. The intermediary files go to the same place for all platforms so anytime you change your platform you'll need to clean first.
