### ISSUE TITLE
This game will not run on the hardware found

### ISSUE THREAD

**Issue by Axiphel** [libretro/mgba#40]
Dragon Ball Z - The Legacy of Goku II

Attempting to go into the overworld map gives the message 'this game will not run on the hardware found' and resets the game. Only solution I've found is to change the save file type to EEPROM which the libretro port doesn't seem to support.

**Comment by sergiobenrocha2** [comment]
Please, report this kind of bugs in the upstream next time: https://github.com/mgba-emu/mgba/issues

@endrift

**Comment by Axiphel** [comment]
I posted it here because in the standalone version this is a non-issue. You can change the save file type in mGBA but you can't in the libretro core which makes this a libretro issue really, doesn't it?

**Comment by endrift** [comment]
No, it should work out of the box. I'll need to add an override to the core that Libretro can downstream.

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#33
