### ISSUE TITLE
Solar sensor not working

### ISSUE THREAD

**Issue by Axiphel** [libretro/mgba#41]
Boktai's sun bar doesn't rise with the solar sensor level.

**Comment by sergiobenrocha2** [comment]
It's working here, you need to Quick Menu --> Options --> Solar Sensor level = 10 or other different than 0

**Comment by sergiobenrocha2** [comment]
Actually it's increasing the value only with R3 button in 0.5.0-beta, menu option is not working. @endrift

@Axiphel L3 for decrease.

**Comment by sergiobenrocha2** [comment]
btw, default value for solar sensor should be 10 instead 0:

```
{ "mgba_solar_sensor_level", "Solar sensor level; 10|0|1|2|3|4|5|6|7|8|9" },
```

**Comment by endrift** [comment]
Uh, what? Why should it be 10? It needs to be 0 when you calibrate it or else it always reads out the wrong value.

**Comment by Axiphel** [comment]
That works sergio. Though the solar sensor level doesn't change when I change it in the quick menu options. (Didn't know there were hotkeys for solar sensor levels). Sorry. :)
