### ISSUE TITLE
how to build for android？

### ISSUE THREAD

**Issue by lcrjeff** [libretro/mgba#46]

**Comment by hizzlekizzle** [comment]
I believe it's:
make -f Makefile.libretro platform=android
from your Android toolchain.

**Comment by lcrjeff** [comment]
thanks

**Comment by fr500** [comment]
it's more like
make -f Makefile.android_armv7a platform=android_armv7a -j8
or so

**Comment by lcrjeff** [comment]
thank you ,  built success,
but i am android  app developer, how to user it , android project? where can i find the demo for android ?

**Comment by fr500** [comment]
demo? we don't have a demo, if you want to make a libretro player you need to implement all the callbacks in a native activity

**Comment by lcrjeff** [comment]
thank you ,  i try get it

**Comment by sergiobenrocha2** [comment]
I think we can close it safely right?
