### ISSUE TITLE
[Feature Request] - Support GBA/GBC Games with rumble hardware

### ISSUE THREAD

**Issue by MarcoEstevez** [libretro/mgba#51]
There were a few GBA and GBC games that had small hardware to bring Rumble features  (Drill Dozer.... )

It would be really cool support them om mGBA if you own a capable controller.

**Comment by sergiobenrocha2** [comment]
Eh, mGBA already has this feature.

Btw, next time made a feature request at upstream, this repo is a shallow fork you know?

**Comment by sergiobenrocha2** [comment]
It's working here.

**Comment by meepingsnesroms** [comment]
Does it work on Android phones with motors?

**Comment by sergiobenrocha2** [comment]
RetroArch does not have rumble support there.

**Comment by MarcoEstevez** [comment]
Ok, I see.

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#34
