### ISSUE TITLE
Buildbot does not compile automaticly for android

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/mgba#53]
My turbo fixes havent been compiled in yet so I checked the buildbot and the last version is from a month ago.

**Comment by fr500** [comment]
Fixed the makefile (for armv7a at least) but it still fails to build

http://hastebin.com/emeyakezod.sql
@leiradel can you check the changes I made to cross-makefiles here? can we do that in all the other cores that use these?

**Comment by meepingsnesroms** [comment]
Fixed

**Comment by leiradel** [comment]
@fr500 Sorry for being late to the party. What changes were made to the makefiles?

**Comment by fr500** [comment]
@leiradel I'm no longer doing buildbot stuff, I didn't do anything...

**Comment by sergiobenrocha2** [comment]
@leiradel #56, a7974dc and https://github.com/libretro/mgba/compare/3fa96167e7bd4e21a30f7191114f40bc70b2c181...faaea96f756621f4e4b64a3abfcbbcfba451d584

**Comment by leiradel** [comment]
@sergiobenrocha2 Cool, thanks. I'll update cross-makefiles with those changes.
