### ISSUE TITLE
Segmentation Fault libretro-mgba

### ISSUE THREAD

**Issue by wwark** [libretro/mgba#54]
Hello,

I have this issue 
RetroArch [INFO] :: Redirecting save file to "Jeux/GBA/Slime Morimori Dragon Quest - Shougeki no Shippo Dan (Japan).srm".
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Dec 10 2016
RetroArch [INFO] :: Version: 1.3.6
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Looking for config in: "/home/***/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Config: loading config from: /home/***/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Loading dynamic libretro core from: "/home/***/.config/retroarch/cores/mgba_libretro.so"
RetroArch [INFO] :: Overrides: no core-specific overrides found at /home/***/.config/retroarch/config/mGBA/mGBA.cfg.
RetroArch [INFO] :: Overrides: no game-specific overrides found at /home/***/.config/retroarch/config/mGBA/Slime Morimori Dragon Quest - Shougeki no Shippo Dan (Japan).cfg.
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Remaps: remap directory: /home/***/.config/retroarch/config/remaps
RetroArch [INFO] :: Remaps: no game-specific remap found at /home/***/.config/retroarch/config/remaps/mGBA/Slime Morimori Dragon Quest - Shougeki no Shippo Dan (Japan).rmp.
RetroArch [INFO] :: Remaps: no core-specific remap found at /home/***/.config/retroarch/config/remaps/mGBA/mGBA.rmp.
RetroArch [INFO] :: Redirecting save file to "Jeux/GBA/Slime Morimori Dragon Quest - Shougeki no Shippo Dan (Japan).srm".
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: 	RetroPad, User 1, Button "B (bottom)" => "B"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Y (left)" => "Turbo B"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Select" => "Select"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Start" => "Start"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Up" => "Up"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Down" => "Down"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Left" => "Left"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Right" => "Right"
RetroArch [INFO] :: 	RetroPad, User 1, Button "A (right)" => "A"
RetroArch [INFO] :: 	RetroPad, User 1, Button "X (up)" => "Turbo A"
RetroArch [INFO] :: 	RetroPad, User 1, Button "L" => "L"
RetroArch [INFO] :: 	RetroPad, User 1, Button "R" => "R"
RetroArch [INFO] :: 	RetroPad, User 1, Button "L2" => "Turbo L"
RetroArch [INFO] :: 	RetroPad, User 1, Button "R2" => "Turbo R"
RetroArch [INFO] :: 	RetroPad, User 1, Button "L3" => "Darken Solar Sensor"
RetroArch [INFO] :: 	RetroPad, User 1, Button "R3" => "Brighten Solar Sensor"
RetroArch [INFO] :: Environ GET_RUMBLE_INTERFACE.
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [INFO] :: Loading content file: Jeux/GBA/Slime Morimori Dragon Quest - Shougeki no Shippo Dan (Japan).gba.
RetroArch [INFO] :: Did not find a valid content patch.
RetroArch [INFO] :: CRC32: 0x1194d33b .
RetroArch [INFO] :: Environ GET_VARIABLE mgba_use_bios:
RetroArch [INFO] :: 	ON
RetroArch [INFO] :: Environ GET_VARIABLE mgba_skip_bios:
RetroArch [INFO] :: 	OFF
RetroArch [INFO] :: Environ GET_VARIABLE mgba_idle_optimization:
RetroArch [INFO] :: 	Remove Known
Segmentation fault

gdb
GNU gdb (Debian 7.11.1-2+b1) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from retroarch...done.
(gdb) rub
Undefined command: "rub".  Try "help".
(gdb) run
Starting program: /usr/local/bin/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed8cd700 (LWP 7602)]
[New Thread 0x7fffe5c7f700 (LWP 7638)]
[Thread 0x7fffe5c7f700 (LWP 7638) exited]
[New Thread 0x7fffed8cd700 (LWP 7646)]
[Thread 0x7fffed8cd700 (LWP 7602) exited]

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
__strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
164	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.

BR,
Wark

**Comment by sergiobenrocha2** [comment]
Try "bt full" inside gdb please, after it gets a SIGSEGV

**Comment by meepingsnesroms** [comment]
Contact your OS developer, strncmp is an OS provided function and seems to be missing.

**Comment by Alcaro** [comment]
what, no, that's not what it says, it just says the segfault is somewhere inside strncmp. Most likely a null pointer.

**Comment by meepingsnesroms** [comment]
What's the no such file or directory for then?

**Comment by Alcaro** [comment]
That means ../sysdeps/x86_64/multiarch/strcmp-sse42.S doesn't exist on his machine, which just means he didn't compile glibc himself. The function itself exists, he just doesn't have the source code installed.

**Comment by meepingsnesroms** [comment]
OK,the library is there but the location of the error can't be shown since the source is not available.

**Comment by wwark** [comment]
Hello,

I get mgba from git and compiled it. It runs without issue with the compile version.

The issue come with the version present a this url https://buildbot.libretro.com/nightly/linux/x86_64/latest/mgba_libretro.so.zip

Could you please tell what i have to install in debian ? 

bt full

(gdb) bt full
#0  __strncmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
No locals.
#1  0x00007fffeb581972 in HashTableLookup () from /home/****/.config/retroarch/cores/mgba_libretro.so
No symbol table info available.
#2  0x00007fffeb538a05 in _lookupIntValue () from /home/****/.config/retroarch/cores/mgba_libretro.so
No symbol table info available.
#3  0x00007fffeb53913b in mCoreConfigMap () from /home/****/.config/retroarch/cores/mgba_libretro.so
No symbol table info available.
#4  0x00007fffeb5397cb in mCoreLoadForeignConfig () from /home/****/.config/retroarch/cores/mgba_libretro.so
No symbol table info available.
#5  0x00007fffeb5806ec in retro_load_game () from /home/****/.config/retroarch/cores/mgba_libretro.so
No symbol table info available.
#6  0x000055555558e080 in load_content (additional_path_allocs=0x555556545dc0, special=<optimized out>, content=0x555556435e80, info=0x555556545d90, temporary_content=0x555556200170) at tasks/task_content.c:1214
        i = <optimized out>
        load_info = {info = 0x555556545d90, content = 0x555556435e80, special = 0x0}
#7  content_file_init (temporary_content=0x555556200170) at tasks/task_content.c:1441
        i = <optimized out>
        info = 0x555556545d90
        ret = <optimized out>
        additional_path_allocs = 0x555556545dc0
        content = 0x555556435e80
        special = <optimized out>
        system = 0x555555937e60 <runloop_system>
        global = <optimized out>
#8  content_init () at tasks/task_content.c:1525
No locals.
#9  0x000055555558234f in event_init_content () at command.c:1310
No locals.
#10 command_event_init_core (data=0x55555591ac20 <explicit_current_core_type>) at command.c:1364
        info = {env = 0x5555555a4f90 <rarch_environment_cb>}
        settings = 0x7fffed8ce010
#11 command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT, data=data@entry=0x55555591ac20 <explicit_current_core_type>) at command.c:2138
        content_info = {argc = 0, argv = 0x0, args = 0x0, environ_get = 0x0}
        i = 0
        boolean = false
        settings = <optimized out>
        info = 0x555555937e60 <runloop_system>
#12 0x000055555557e58e in retroarch_main_init (argc=7, argv=argv@entry=0x7fffffff0200) at retroarch.c:1352
No locals.
#13 0x000055555558c700 in content_load (info=0x7fffffff33e0) at tasks/task_content.c:935
        i = <optimized out>
        retval = true
        rarch_argc = 7
        rarch_argv_ptr = 0x7fffffff0200
        rarch_argv = {0x5555563b9a80 "retroarch", 0x555556583d20 "-c", 0x555556540140 "/home/****/.config/retroarch/retroarch.cfg", 0x5555564b66f0 "-L", 0x555556546070 "/home/****/.config/retroarch/cores/mgba_libretro.so", 
          0x5555563c0e10 "-v", 0x5555565441d0 "/home/****/Jeux/gbc/Zelda no Densetsu - Yume o Miru Shima DX (Japan) (Rev B) (SGB Enhanced).gbc", 0x0 <repeats 25 times>}
        argv_copy = {0x5555563b9a80 "retroarch", 0x5555565441d0 "/home/****/Jeux/gbc/Zelda no Densetsu - Yume o Miru Shima DX (Japan) (Rev B) (SGB Enhanced).gbc", 0x555556583d20 "-c", 
          0x555556540140 "/home/****/.config/retroarch/retroarch.cfg", 0x5555564b66f0 "-L", 0x555556546070 "/home/****/.config/retroarch/cores/mgba_libretro.so", 0x5555563c0e10 "-v", 0x0 <repeats 25 times>}
        rarch_argc_ptr = 0x7fffffff01f4
        wrap_args = 0x5555563c5200
#14 task_load_content (content_info=content_info@entry=0x7fffffff3460, launched_from_menu=launched_from_menu@entry=false) at tasks/task_content.c:1607
        name = '\000' <repeats 4095 times>
        msg = '\000' <repeats 4095 times>
        fullpath = 0x555555939ba0 <runloop_fullpath> "/home/****/Jeux/gbc/Zelda no Densetsu - Yume o Miru Shima DX (Japan) (Rev B) (SGB Enhanced).gbc"
#15 0x000055555558e26d in command_event_cmd_exec (data=0x5555563b9f70) at tasks/task_content.c:1701
        content_info = {argc = 0, argv = 0x0, args = 0x0, environ_get = 0x55555558b420 <menu_content_environment_get>}
        fullpath = 0x555555939ba0 <runloop_fullpath> "/home/****/Jeux/gbc/Zelda no Densetsu - Yume o Miru Shima DX (Japan) (Rev B) (SGB Enhanced).gbc"
#16 task_push_content_load_default (core_path=core_path@entry=0x7fffffff3550 "/home/****/.config/retroarch/cores/mgba_libretro.so", 
    fullpath=0x5555563b9f70 "/home/****/Jeux/gbc/Zelda no Densetsu - Yume o Miru Shima DX (Japan) (Rev B) (SGB Enhanced).gbc", content_info=content_info@entry=0x7fffffff4550, type=type@entry=CORE_TYPE_PLAIN, 
    mode=mode@entry=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU, cb=cb@entry=0x0, user_data=0x0) at tasks/task_content.c:1833
        loading_from_menu = <optimized out>
#17 0x000055555560c7e2 in generic_action_ok_file_load (content_enum_idx=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU, action_type=CORE_TYPE_PLAIN, fullpath=<optimized out>, 
    corepath=0x7fffffff3550 "/home/****/.config/retroarch/cores/mgba_libretro.so") at menu/cbs/menu_cbs_ok.c:784
        content_info = {argc = 0, argv = 0x0, args = 0x0, environ_get = 0x55555558b420 <menu_content_environment_get>}
---Type <return> to continue, or q <return> to quit---
#18 action_ok_playlist_entry_collection (path=<optimized out>, label=<optimized out>, type=<optimized out>, idx=<optimized out>, entry_idx=3) at menu/cbs/menu_cbs_ok.c:1002
        selection = 0
        playlist_info = {data = 0x5555565955d0, idx = 3}
        new_core_path = "/home/****/.config/retroarch/cores/mgba_libretro.so", '\000' <repeats 4044 times>
        selection_ptr = 3
        playlist = <optimized out>
        playlist_initialized = false
        entry_path = 0x5555563b9f70 "/home/****/Jeux/gbc/Zelda no Densetsu - Yume o Miru Shima DX (Japan) (Rev B) (SGB Enhanced).gbc"
        entry_label = 0x0
        core_path = 0x5555563b9aa0 "/home/****/.config/retroarch/cores/mgba_libretro.so"
        core_name = 0x555556595280 "mGBA"
        tmp_playlist = 0x5555565955d0
        menu = 0x555556350ef0
#19 0x00005555555f281d in menu_entry_action (entry=entry@entry=0x7fffffff5660, i=<optimized out>, action=action@entry=MENU_ACTION_OK) at menu/menu_entry.c:382
        ret = 0
        selection_buf = 0x555556362220
        cbs = <optimized out>
#20 0x0000555555626ab5 in generic_menu_iterate (data=0x555556350ef0, userdata=<optimized out>, action=MENU_ACTION_OK) at menu/drivers/menu_generic.c:355
        selection = 0
        entry = {
          path = "Run\000\000\000\000\000\025qdUUU\000\000\200;\236UUU\000\000\020Y\377\377\377\177\000\000\200;\236UUU\000\000\300V\377\377\377\177\000\000@W\377\377\377\177\000\000\070\004\000\000\000\000\000\000\017\000\000\000\000\000\000\000i\211^UUU\000\000\200;\236U\000\000\006D\000\000\bD\000\000\354C \000lUUU\000\000\320\312\377\377\377\177\000\000\000\000lUUU\000\000\000\000lUUU\000\000\004\000\000\000\000\000\000\000\000\000\200?\000\000\200\277\000\000\000@", '\000' <repeats 24 times>, "\063\063\263>", '\000' <repeats 12 times>, "\063\063\263>", '\000' <repeats 12 times>..., label = "collection", '\000' <repeats 742 times>..., rich_label = '\000' <repeats 4095 times>, 
          value = '\000' <repeats 752 times>..., entry_idx = 3, enum_idx = MENU_ENUM_LABEL_RUN, idx = 0, type = 7, spacing = 0}
        label = 0x555556582ec0 "null"
        ret = 0
        label_hash = 0
        hash = <optimized out>
        enum_idx = MSG_UNKNOWN
        menu = 0x555556350ef0
        menu_stack = 0x555556362200
        selection_buf = <optimized out>
#21 0x00005555555eecac in menu_driver_ctl (state=state@entry=RARCH_MENU_CTL_ITERATE, data=data@entry=0x7fffffffe7d0) at menu/menu_driver.c:851
        iterate = 0x7fffffffe7d0
#22 0x000055555558973a in runloop_iterate_menu (sleep_ms=0x7fffffffe89c, action=MENU_ACTION_OK) at runloop.c:1311
        iter = {action = MENU_ACTION_OK, pointer = {x = 32767, y = 0, touch = 208}, mouse = {x = 22083, y = 21845, buttons = {left = false, right = false}, wheel = {up = false, down = 82}}}
        settings = 0x7fffed8ce010
        focused = true
        is_idle = false
#23 runloop_iterate (sleep_ms=0x7fffffffe89c) at runloop.c:1462
        i = <optimized out>
        cmd = {state = {{type = <optimized out>, state = <optimized out>}, {type = <optimized out>, state = 0}, {type = <optimized out>, state = <optimized out>}}}
        current = <optimized out>
        target = <optimized out>
        to_sleep_ms = <optimized out>
        last_input = {type = 0, state = 256}
        cmd_ptr = 0x7fffffffe7a0
        frame_limit_minimum_time = 16667
        frame_limit_last_time = 1312808713
        settings = <optimized out>
#24 0x000055555557abf0 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:122
        sleep_ms = 0
        args = 0x0
        argc = <optimized out>
        argv = <optimized out>
        data = 0x0
        args = 0x0
#25 0x00007ffff44a22b1 in __libc_start_main (main=0x555555578120 <main>, argc=1, argv=0x7fffffffe9c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe9b8) at ../csu/libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -2274590100839670103, 93824992379184, 140737488349632, 0, 0, -5387891293622575447, -5387912632851833175}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffe9d8, 
              0x7ffff7ffe168}, data = {prev = 0x0, cleanup = 0x0, canceltype = -5672}}}
        not_first_call = <optimized out>
#26 0x000055555557815a in _start ()
No symbol table info available.

BR,
Wark.

**Comment by sergiobenrocha2** [comment]
Use can use some markdown to this trace you know

Were you using mgba core from debian repo ?

**Comment by sergiobenrocha2** [comment]
What GCC version are you using? Buildbot uses gcc6

**Comment by wwark** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.2.1-5' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.1 20161124 (Debian 6.2.1-5)

**Comment by sergiobenrocha2** [comment]
Btw, why don't you use mgba core from debian repo?

The core from the buildbot is working here, Ubuntu 14.04.

**Comment by wwark** [comment]
yes i could use it but it is a old version of mgba.

I have a workaround if i compile myself from the repository so i close this issue.

Thanks !

**Comment by sergiobenrocha2** [comment]
It's old, but for gba emulation it's pretty the same thing, and you'll don't have issue # 43
