### ISSUE TITLE
Segfault with specific ARM optimizations

### ISSUE THREAD

**Issue by zgoda** [libretro/mgba#58]
Platform: Allwinner H3 (armv7-a, NEON, VFP4)

According to spec, this platform supports `-mfpu=neon-vfpv4` GCC flag. Compilation succeeds but resulting core segfaults. Removing FPU flag produces working core.

Failing optimization flags set: `-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe`, this is suggested for this platform by manufacturer.

Other libretro cores work fine with these flags, checked with snes9x-next, mupen64 and desmume.

**Comment by endrift** [comment]
I really wouldn't suggest `-funsafe-math-optimizations`. I don't believe it affects performance in mGBA anyway, but it can lead to, well, unsafe things happening.

Can you gather a backtrace from where it's crashing?

**Comment by zgoda** [comment]
Will try to find specific place where it dies.

I found NEON SIMD has something to do here. For Cortex-A7 cores recommended fpu flags are `neon-vfpv4`, `vfpv4` (without SIMD) or `vfpv4-d16` (without SIMD, 16 registers less) and only `neon-vfpv4` build segfaults. And this issue is related to this specific SOC, because exactly the same flags set work for eg. Raspberry Pi 2 (ARMv7-a, Cortex-A7) so I'm positive it's either bug in GCC or buggy SIMD implementation.

As for `unsafe-math-optimizations` flag, recommended `fast-math` flag sets it among other things on this platform so I guess it should be harmless but I will check this anyway.

I will try to produce any core dump for debugging.

**Comment by fr500** [comment]
This issue was moved to libretro/libretro-meta#19
