### ISSUE TITLE
Pokemon Pinball GBA hangs

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mgba#66]
It seems to be a libretro only bug I reported upstream by mistake: https://github.com/mgba-emu/mgba/issues/820

As soon as you start playing the cpu usage skyrocket and game slows down until it halts.
Just got a blue screen while testing it with task manager open.

Rom is from No-Intro set, different versions act the same.

mGBA-libretro 0.6.0
Windows 7 x64
Core i5-3570K, Nvidia GTX-770, OpenGL

**Comment by sergiobenrocha2** [comment]
It's working fine on Linux and Android, CRC B992A3C0

**Comment by sergiobenrocha2** [comment]
I can't reproduce on windows 10. How much time does it take to hang?

**Comment by Tatsuya79** [comment]
Really fast, half way when the animation goes down the table before you can play you can see it happen.

**Comment by sergiobenrocha2** [comment]
Take a look at #70, the guy using the wrong bios

**Comment by Tatsuya79** [comment]
Unrelated. 
I tried with or without the bios recommended in the core info file and the bug still happens.
