### ISSUE TITLE
Graphics corrupt at title screen and begging of game in Metroid Zero Mission

### ISSUE THREAD

**Issue by SedrynTyros** [libretro/mgba#70]
I have an old copy of "mgba_libretro.dll" from January 15, 2017 and that version of the core works fine.  But the recent versions of the core have this problem of graphics corrupt at the start of Metroid Zero Mission.  If you have a copy of the game, the problem is very easy to reproduce.

**Comment by sergiobenrocha2** [comment]
Testing the game, CRC 5C61A844, it's working here on Linux and Android. Tried with and without BIOS.

**Comment by SedrynTyros** [comment]
Interesting .... any speculation on why the core from January would work fine on my system but not the latest version of the core?  I've tested on RetroArch v1.6.7 for Windows, on Windows 10, using OpenGL video.

**Comment by sergiobenrocha2** [comment]
It's working on windows 10 too

**Comment by SedrynTyros** [comment]
No, it isn't.  Just confirmed, current core still shows corruption, old core doesn't.  "Nvidia GeForce v384.94 x64 (Win10)" drivers on ASUS GTX 1070 card.  Not other app shows problems.  The problem is, without question, with this current core.  The old one works fine.

**Comment by sergiobenrocha2** [comment]
Show us an image please. What's the hash of your version (next to 0.6.0)? Here it's 7c1ae396

Shouldn't be the issue, but what's your retroarch version? 32 or 64-bit?

**Comment by SedrynTyros** [comment]
![metroid - zero mission u -170825-203757](https://user-images.githubusercontent.com/11150165/29738350-7efe6db8-89d5-11e7-8c7f-dc66c2f708f7.png)

**Comment by SedrynTyros** [comment]
![metroid - zero mission u -170825-203805](https://user-images.githubusercontent.com/11150165/29738361-854ee008-89d5-11e7-9d5a-a933228472eb.png)

**Comment by SedrynTyros** [comment]
![metroid - zero mission u -170825-203808](https://user-images.githubusercontent.com/11150165/29738363-8c4b1c0a-89d5-11e7-92f5-582b6466d894.png)

**Comment by SedrynTyros** [comment]
![metroid - zero mission u -170825-203814](https://user-images.githubusercontent.com/11150165/29738365-95c256f4-89d5-11e7-8aa7-233389076704.png)

**Comment by SedrynTyros** [comment]
![metroid - zero mission u -170825-203821](https://user-images.githubusercontent.com/11150165/29738367-9be11700-89d5-11e7-99cf-eac236ed0c05.png)

**Comment by SedrynTyros** [comment]
Just to reiterate, I have an old copy of "mgba_libretro.dll" from January 15, 2017 and that version of the core works fine.  I see none of these problems with that core.

**Comment by SedrynTyros** [comment]
RetroArch v1.6.7 for Windows 10, 64-Bit.

**Comment by SedrynTyros** [comment]
Hang on.  I just tried with "mgba_use_bios = "OFF""  and get no corruption.  Maybe there's something wrong with the BIOS file I'm using.

**Comment by SedrynTyros** [comment]
Interesting .... looks like the BIOS file that worked fine with the v0.5.2 core didn't like the newer v0.6.0 core.

Problematic BIOS has CRC 15E1F676 [GBA BIOS (J).bin].  I replaced it with BIOS having CRC A6473709 [GBA BIOS from NDS (Rev 2 Firmware).bin.  Now, everything's working fine with the newer core.

**Comment by SedrynTyros** [comment]
Gotcha.  I have that CRC 81977335 as well so I'll go ahead and use that one since it's the one you test with.
