### ISSUE TITLE
Problem with fast forward in retropie

### ISSUE THREAD

**Issue by farso92** [libretro/mgba#78]
hi i use mgba in my retropie...but when i launch the game and i activate fast forward with hotkeys combination the speed don't change....the strange thing is that if i activate fast forward immediately i can see the first written "gamboy nintendo" came faster as if the problem was in the gba image file

**Comment by hizzlekizzle** [comment]
Fast-forward works by disabling vsync and audio sync to let the core run as fast as it can. My guess is that it simply can't run games any faster on that hardware.

**Comment by meepingsnesroms** [comment]
The gameboy logo is not speed intensive thus the Pi is fast enough to fastforward it, it isnt fast enough to fastforward the game however.
