### ISSUE TITLE
Frameskip Option for mGBA Core?

### ISSUE THREAD

**Issue by ShabbaRetro** [libretro/mgba#85]
Hello,

I have performance issues with my mid-range android device.
I found that mGBA has a frameskip option:
``-s, --frameskip N
(Skip every N frames)``

Can you add this option to the mGBA Core, please?

**Comment by endrift** [comment]
I can look into adding this upstream. It can make games a bit buggy though.

**Comment by ShabbaRetro** [comment]
Thank you, it would be great if it works.

**Comment by endrift** [comment]
Added upstream: https://github.com/mgba-emu/mgba/commit/cee6569bde476ea94e05237baf62d3d4ce1d2cf9

Will need someone else to merge it downstream though.

**Comment by hizzlekizzle** [comment]
Closed by https://github.com/libretro/mgba/commit/9a54cd53a63b5c09fd8bd18b1ad0e8d32fe85737

Thanks to endrift for adding this upstream! :)
