### ISSUE TITLE
[Graphics] Yoshi Topsy-Turvy - Yoshi's sprite

### ISSUE THREAD

**Issue by llethas** [libretro/mgba#86]
Specs: i3 7100U, 4GB RAM, Intel HD 620
OS: Manjaro 17.1.1 Hakoila x64
RetroArch: 1.7.0
mgba(libretro): 05e2ff4

ROM CRC32: E64C265C

![screenshot_20180111_184919](https://user-images.githubusercontent.com/35349081/34847291-fd040a62-f701-11e7-85d6-8540f106d17f.png)

Save state mGBA - [Yoshi Topsy-Turvy.ss1.zip](https://github.com/libretro/mgba/files/1624096/Yoshi.Topsy-Turvy.ss1.zip)
Save state RetroArch - [Yoshi Topsy-Turvy.state.zip](https://github.com/libretro/mgba/files/1624098/Yoshi.Topsy-Turvy.state.zip)

**Comment by endrift** [comment]
Hm, might be a 16-bit color issue. Does this occur on the 3DS stand-alone version?

**Comment by llethas** [comment]
Hey. Unfortunately I don't have a 3DS, so I can't test it.

Btw, I forgot to mention this only happens during the cutscenes. I've only tested the first cutscene, though. Also, the game uses tilt mechanics, but there's a patch to use L and R instead.

Patch - [Yoshi Topsy-Turvy.ips.zip](https://github.com/libretro/mgba/files/1624255/Yoshi.Topsy-Turvy.ips.zip)

**Comment by endrift** [comment]
Looks like this was already fixed upstream. I'll file a PR to sync downstream.

**Comment by llethas** [comment]
It's indeed fixed

![screenshot_20180113_102117](https://user-images.githubusercontent.com/35349081/34906041-dfa3a0ae-f84b-11e7-85a6-86be3927e771.png)

Thank you.
