### ISSUE TITLE
Sound regression?

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mgba#95]
I've just noticed some sound issue playing Sonic advance.
It's like the bass is loud but high are really low (sonic dash sound is barely audible) + sound seems imprecise, like there's some noise on top.

win7 x64 current core

VBA-Next/MGBA stand-alone 0.6.1 sounds better

**Comment by Awakened0** [comment]
Yeah, I notice this too. The older build of the core I have (05e2ff4d) sounds much more balanced.

**Comment by fr500** [comment]
wouldn't it be better to open the issue upstream?

**Comment by bryc** [comment]
Definitely a regression in the libretro port. I am experiencing the same thing, and I noticed the desktop mGBA version of mGBA is unaffected.  The pulse wave channel is too loud and overpowers the PCM channels.

[Here](https://github.com/mgba-emu/mgba/files/1776231/firered.zip) is a sound comparison of the various GBA cores. mGBA sticks out like a sore thumb regarding the pulse wave, you can hardly hear the cymbal crashes at all.

**Comment by endrift** [comment]
It's probably just the branch. I can take a look at differences between 0.6.x and master

**Comment by endrift** [comment]
Found it, it affects the 0.6 only, but regressed after 0.6.1 came out. Fixed in fd60a1caff2c80ede9c2acda6986dea09abea5f0 so once you sync to 0.6 again it'll be fixed.

**Comment by Tatsuya79** [comment]
I think we're good now.
Thank you, closing this.
